version: '3.8'

services:
  app:
    image: 'app'
    build:
      context: ./1_microservices/ms-client/
      dockerfile: Dockerfile
    container_name: app
    restart: always
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
    ports:
      - "8090:8090"

  mysqldb:
    image: 'mysql'
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=clientdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"