version: '3.8'

services:
  ms-client:
    image: 'ms-client'
    build:
      context: ./1_microservices/ms-client/
      dockerfile: Dockerfile
    container_name: ms-client
    restart: always
    depends_on:
      - mysqldb
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306
      - MS_PHOTO_HOST_FEIGN=ms-photo
      - MS_PHOTO_PORT_FEIGN=8091
    ports:
      - "8090:8090"

  ms-photo:
    image: 'ms-photo'
    build:
      context: ./1_microservices/ms-photo/
      dockerfile: Dockerfile
    container_name: ms-photo
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=photodb
    ports:
      - "8091:8091"

  mysqldb:
    image: 'mysql'
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=clientdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  
  mongodb:
    image: "mongo"
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"