server:
  port: 8090

spring:
  application:
    name: ms-client

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/clientdb?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update

resilience4j.circuitbreaker:
  instances:
    ms-photo-cb:
      registerHealthIndicator: true
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      permittedNumberOfCallsInHalfOpenState: 4
      minimumNumberOfCalls: 10
      waitDurationInOpenState: 5s
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 10
      failureRateThreshold: 50

appDescription: "API Client"
appVersion: "1.0.0"

url-ms-photo-feign: http://${MS_PHOTO_HOST_FEIGN:localhost}:${MS_PHOTO_PORT_FEIGN:8091}